n = input('Digite algo: ')
print('O tipo deste valor é: ', type(n))
print('O valor é numérico? ', n.isnumeric())
print('O valor é alphabético? ', n.isalpha())
print('O valor é alphanumérico? ', n.isalnum())
print('O valor é maúisculo? ', n.isupper())
print('O valor é minúsculo? ', n.islower())
print('O valor é um espaço? ', n.isspace())
print('O valor é printavel? ', n.isprintable())
print('O valor é um título? ', n.istitle())