nome = str(input('Digite seu nome completo: ')).strip()
print('Analisando seu nome...')
print('O nome maiúsculo é: {}'.format(nome.upper()))
print('O nome minúsculo é: {}'.format(nome.lower()))
print('O tamanho do nome é: {}'.format(len(nome) - nome.count(' ')))
print('Seu primeiro nome tem {} letras'.format(nome.find(' ')))