campeonato = ('Corinthians', 'Palmeiras', 'Santos', 'Grêmio', 'Cruzeiro', 'Flamengo', 'Vasco', 'Chapecoense', 'Atlético-MG', 'Botafogo', 'Bahia', 'São Paulo', 'Fluminense', 'Sport Recife', 'Coritiba', 'Avaí', 'Ponte Preta', 'Atlético-PR', 'Ceará SC', 'Vitória')
print('-=' * 15)
print(f'Lista de times do Brasileirão: {campeonato}')
print('-=' * 15)
print(f'Os 5 primeiros são: {campeonato[:5]}')
print('-=' * 15)
print(f'Os 4 últimos são: {campeonato[-4:]}')
print('-=' * 15)
print(f'Times em ordem alfabética: {sorted(campeonato)}')
print('-=' * 15)
print(f'O Chapecoense está na {campeonato.index("Chapecoense") +1}ª posição.')
